# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baseten < Formula
  desc "CLI for Baseten"
  homepage "https://github.com/basetenlabs/baseten-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/basetenlabs/baseten-cli/releases/download/v1.1.0/baseten_1.1.0_darwin_amd64.tar.gz"
      sha256 "d7ed7d71f49aa29a8cf579f524bf0fe0d027f56a4479c2be7934b77dfd3a63c8"

      define_method(:install) do
        bin.install "baseten"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/basetenlabs/baseten-cli/releases/download/v1.1.0/baseten_1.1.0_darwin_arm64.tar.gz"
      sha256 "e4f3878cd2c30dd995fb71c670d10f8dec41d80b07ef7ab3103ac69c19dc26e3"

      define_method(:install) do
        bin.install "baseten"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/basetenlabs/baseten-cli/releases/download/v1.1.0/baseten_1.1.0_linux_amd64.tar.gz"
      sha256 "38762c1acdeaf55a33f2b0d6c5cc3417feb6fbf45143db7430a1eb2a2aec05d1"
      define_method(:install) do
        bin.install "baseten"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/basetenlabs/baseten-cli/releases/download/v1.1.0/baseten_1.1.0_linux_arm64.tar.gz"
      sha256 "ffc8e8b44e370af0ea88376e2b0eaa3821f1b472f90a412e609b0a578686bfd9"
      define_method(:install) do
        bin.install "baseten"
      end
    end
  end

  test do
    system "#{bin}/baseten", "--version"
  end
end
