# typed: strict
# frozen_string_literal: true

# This file is generated by Baseten Switch release automation. DO NOT EDIT.
class BasetenSwitch < Formula
  desc "Local gateway routing AI coding harnesses between native providers and Baseten"
  homepage "https://github.com/basetenlabs/baseten-switch"
  url "https://github.com/basetenlabs/baseten-switch/releases/download/v0.6.0/baseten-switch_0.6.0_darwin_universal.zip"
  sha256 "df162bcd65cccdc5f2fa78e38c950bd94fdf2694ca3913d378c70a471e04fc11"
  license "MIT"

  depends_on "basetenlabs/baseten/baseten"
  depends_on :macos

  on_macos do
    depends_on macos: :ventura
  end

  def install
    bin.install "bin/baseten-switch"
    pkgshare.install "Baseten Switch.app.zip"
    pkgshare.install "LICENSE", "THIRD_PARTY_NOTICES.md"
  end

  def caveats
    <<~EOS
      Baseten Switch is beta software. The bundled Mac app is ad-hoc signed
      and is not notarized by Apple.

      If macOS blocks the app, try to open it once, then open System Settings >
      Privacy & Security and click Open Anyway. Managed Macs may prohibit this
      override; contact your administrator if Open Anyway is unavailable.
    EOS
  end

  test do
    assert_match "baseten-switch v#{version}", shell_output("#{bin}/baseten-switch --version")
    assert_path_exists pkgshare/"Baseten Switch.app.zip"
    assert_path_exists pkgshare/"LICENSE"
    assert_path_exists pkgshare/"THIRD_PARTY_NOTICES.md"
  end
end
