# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baseten < Formula
  desc "CLI for Baseten"
  homepage "https://github.com/basetenlabs/baseten-cli"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/basetenlabs/baseten-cli/releases/download/v1.3.0/baseten_1.3.0_darwin_amd64.tar.gz"
      sha256 "b290bebecd3509605a759444b879f268503ae2ad3b8c8fb44947908437407386"

      define_method(:install) do
        bin.install "baseten"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/basetenlabs/baseten-cli/releases/download/v1.3.0/baseten_1.3.0_darwin_arm64.tar.gz"
      sha256 "68ba46635c2665f8542cbc398b5808ffce8b64cbb3971a84a1f0062697bb075e"

      define_method(:install) do
        bin.install "baseten"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/basetenlabs/baseten-cli/releases/download/v1.3.0/baseten_1.3.0_linux_amd64.tar.gz"
      sha256 "caa448cd5b725d45a9cc5d01cc7df21a67b3f12573b35aba0c5e1f24bb1c6807"
      define_method(:install) do
        bin.install "baseten"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/basetenlabs/baseten-cli/releases/download/v1.3.0/baseten_1.3.0_linux_arm64.tar.gz"
      sha256 "c78e4fd7452721a0d7f5cde7bb7e18834d3c185cda7cef0e316c2df1648a400a"
      define_method(:install) do
        bin.install "baseten"
      end
    end
  end

  test do
    system "#{bin}/baseten", "--version"
  end
end
